// Regenerates src/data/photos.ts by inlining every image in public/plats/
// as a data URI keyed by filename (without extension = recipe id / image key).
// Run: node scripts/build-photos.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname, extname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dir = join(root, 'public', 'plats')
const mime = { '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp' }

const entries = {}
for (const file of readdirSync(dir)) {
  const ext = extname(file).toLowerCase()
  if (!mime[ext]) continue
  const id = basename(file, ext)
  const b64 = readFileSync(join(dir, file)).toString('base64')
  entries[id] = `data:${mime[ext]};base64,${b64}`
}

const lines = Object.keys(entries).sort().map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(entries[k])},`)
const out = `// Inlined dish photos as data URIs.
// These render in every environment — including the offline single-file
// artifact preview where external image URLs are blocked by CSP.
// Generated in curated batches (AI food photography). Dishes without an
// entry here fall back to public/plats/<id>.jpg, then to the emoji tile.
// This file is regenerated by scripts/build-photos.mjs — do not hand-edit.
export const INLINE_PHOTOS: Record<string, string> = {
${lines.join('\n')}
}
`
writeFileSync(join(root, 'src', 'data', 'photos.ts'), out)
console.log(`Inlined ${Object.keys(entries).length} photo(s) into src/data/photos.ts`)
