// Regenerates src/data/photos.ts by inlining images in public/plats/ as data URIs.
// Strategy:
//   - .webp files (AI-generated, high quality) → always inlined
//   - .jpg/.jpeg/.png (TheMealDB/Wikimedia imports) → served as static files on
//     Netlify via public/plats/<id>.jpg; NOT inlined (keeps artifact under 16 MB).
// Run: node scripts/build-photos.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname, extname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dir = join(root, 'public', 'plats')
const mimeMap = {
  '.webp': 'image/webp',
  // .jpg / .png are served as static files; not inlined here
}

const entries = {}
for (const file of readdirSync(dir)) {
  const ext = extname(file).toLowerCase()
  const mime = mimeMap[ext]
  if (!mime) continue               // skip .jpg/.png — they'll be served as static files
  const id = basename(file, ext)
  const b64 = readFileSync(join(dir, file)).toString('base64')
  entries[id] = `data:${mime};base64,${b64}`
}

const lines = Object.keys(entries).sort().map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(entries[k])},`)
const out = `// Inlined dish photos as data URIs.
// Only .webp files (AI-generated) are inlined — they render in every environment
// including the offline artifact preview (CSP blocks external URLs there).
// .jpg photos from TheMealDB/Wikimedia are served as static files in public/plats/
// on the Netlify build (no CSP restriction there).
// This file is regenerated by scripts/build-photos.mjs — do not hand-edit.
export const INLINE_PHOTOS: Record<string, string> = {
${lines.join('\n')}
}
`
writeFileSync(join(root, 'src', 'data', 'photos.ts'), out)
const n = Object.keys(entries).length
console.log(`Inlined ${n} .webp photo(s) into src/data/photos.ts`)
console.log(`(.jpg/.png files in public/plats/ are served as static files on Netlify)`)
