/**
 * Phase 3 — Merge translated MealDB recipes into recipes_mealdb.ts
 * Only keeps recipes that have a YouTube tutorial ID (565/792).
 *
 * Usage: node scripts/merge-recipes.mjs
 * Prerequisites: translate-mealdb.mjs must have completed first.
 */
import { writeFileSync, readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const rawPath = join(root, 'src', 'data', 'mealdb_raw.json')

const meals = JSON.parse(readFileSync(rawPath, 'utf8'))
const withVideo = meals.filter((m) => m.youtubeId)

console.log(`📊 Total meals in raw data: ${meals.length}`)
console.log(`🎬 With YouTube videos: ${withVideo.length}`)
console.log(`⏩ Skipped (no video): ${meals.length - withVideo.length}`)

function jsStr(s) {
  return JSON.stringify(s ?? '')
}

function entriesToTs(arr) {
  return arr.map((v) => JSON.stringify(v)).join(', ')
}

const lines = []
lines.push(`// AUTO-GENERATED by merge-recipes.mjs — DO NOT EDIT`)
lines.push(`// ${withVideo.length} recipes from TheMealDB — only those with YouTube tutorials`)
lines.push(`import type { Recipe } from './types'`)
lines.push(``)
lines.push(`export const MEALDB_RECIPES: Recipe[] = [`)

for (const m of withVideo) {
  const nameFR = m.nameFR && m.nameFR !== m.nameEN ? m.nameFR : m.nameEN
  const nameAR = m.nameAR && m.nameAR !== m.nameEN ? m.nameAR : m.nameEN

  // Real cooking steps in English — shown as-is (bilingual field set to EN for both)
  const stepsEN = Array.isArray(m.stepsEN) ? m.stepsEN.slice(0, 12) : []
  const hasSteps = stepsEN.length > 0

  const ingLines = (m.ingredients || [])
    .map((i) => `      { id: ${jsStr(i.id)}, qtyPerPerson: ${i.qtyPerPerson} }`)
    .join(',\n')

  const eqArr = (m.equipment || []).map((e) => jsStr(e)).join(', ')

  const parts = []
  parts.push(`    id: ${jsStr(m.id)}`)
  parts.push(`    name: { fr: ${jsStr(nameFR)}, ar: ${jsStr(nameAR)} }`)
  parts.push(`    emoji: ${jsStr(m.emoji)}`)
  // Map any mealType not in our type system to the nearest valid slot
  const MEAL_TYPE_MAP = { dessert: 'gouter', breakfast: 'petit_dejeuner', starter: 'petit_dejeuner', side: 'dejeuner' }
  const mealType = MEAL_TYPE_MAP[m.mealType] ?? m.mealType ?? 'diner'
  parts.push(`    mealType: ${jsStr(mealType)}`)
  parts.push(`    tags: [${entriesToTs(m.tags || [])}]`)
  parts.push(`    timeMin: ${m.timeMin || 30}`)
  parts.push(`    kcal: ${m.kcal || 400}, protein: ${m.protein || 20}, carbs: ${m.carbs || 40}, fat: ${m.fat || 15}`)
  parts.push(`    ingredients: [\n${ingLines}\n    ]`)
  parts.push(`    equipment: [${eqArr}]`)
  parts.push(`    vegetarian: ${!!m.vegetarian}, pescetarian: ${!!m.pescetarian}`)
  parts.push(`    glutenFree: ${!!m.glutenFree}, lactoseFree: ${!!m.lactoseFree}, pregnancySafe: ${!!m.pregnancySafe}`)
  parts.push(`    youtubeId: ${jsStr(m.youtubeId)}`)
  parts.push(`    image: ${jsStr(m.id)}`)

  if (hasSteps) {
    const stepsJson = JSON.stringify(stepsEN.map((s) => ({ fr: s, ar: s })), null, 6)
    parts.push(`    steps: ${stepsJson.replace(/\n/g, '\n    ')}`)
  }

  lines.push(`  {`)
  for (const p of parts) lines.push(p + ',')
  lines[lines.length - 1] = lines[lines.length - 1].replace(/,$/, '') // remove last trailing comma
  lines.push(`  },`)
}

lines.push(`]`)
lines.push(``)

writeFileSync(join(root, 'src', 'data', 'recipes_mealdb.ts'), lines.join('\n'))
console.log(`\n✅ recipes_mealdb.ts written with ${withVideo.length} recipes`)
console.log(`   → These all have YouTube tutorial videos`)
console.log(`\n👉 Next: rebuild the app (npm run build in romi/)`)
